# Generated by Django 2.0.2 on 2018-06-08 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0002_dating_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="dating",
            options={"managed": True},
        ),
    ]
