# Generated by Django 2.0.13 on 2020-03-04 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0019_photogallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonarticle",
            options={
                "verbose_name": "Běžné příspěvky",
                "verbose_name_plural": "Běžné příspěvky",
            },
        ),
        migrations.AlterModelOptions(
            name="creativepage",
            options={"verbose_name": "Rubrika", "verbose_name_plural": "Rubriky"},
        ),
        migrations.AlterModelOptions(
            name="creativepageconcept",
            options={
                "verbose_name": "Koncept rubriky",
                "verbose_name_plural": "Koncepty rubriky",
            },
        ),
    ]
