# Generated by Django 2.0.13 on 2020-10-11 19:05

import ddcz.models.magic
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0028_links_encoding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alchpredmety",
            options={},
        ),
        migrations.AddField(
            model_name="alchpredmety",
            name="precteno",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="bcz",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="datum",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="dosah_ucinku",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="nalezeni",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="nebezpecnost",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="sfera",
            field=ddcz.models.magic.MisencodedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="sila",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="skupina",
            field=ddcz.models.magic.MisencodedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="tisknuto",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="trvani",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="uroven_vyrobce",
            field=ddcz.models.magic.MisencodedCharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="vyroba",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="zaklad",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alchpredmety",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
    ]
