# Generated by Django 2.0.13 on 2020-10-11 20:17

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0031_alchtools_signular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")], max_length=1
            ),
        ),
    ]
