# Generated by Django 2.0.13 on 2020-11-09 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0041_download_rename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downloaditem",
            options={"verbose_name_plural": "Downloads"},
        ),
    ]
