# Generated by Django 2.0.13 on 2020-11-09 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0046_quests"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dobrodruzstvi",
            new_name="Quest",
        ),
    ]
