# Generated by Django 2.0.13 on 2021-04-07 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0055_diskuze_rename"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
            DELETE FROM 
                `diskuze`
            WHERE
                datum < "2000-01-01 01:01"
            """
                )
            ],
            reverse_sql=[],
        ),
    ]
