# Generated by Django 2.0.13 on 2021-04-13 13:57

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0058_editorarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="sm",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="SM", max_length=50, null=True
            ),
        ),
    ]
