# Generated by Django 2.0.13 on 2021-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0066_mentat_fix_autoincrement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentatnewbie",
            name="django_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mentatnewbie",
            name="newbie_id",
            field=models.IntegerField(),
        ),
    ]
