# Generated by Django 2.0.13 on 2021-04-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0068_mentat_autofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentatnewbie",
            name="mentat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentat",
                to="ddcz.UserProfile",
                db_column="mentat_id",
                db_constraint=False,
            ),
        ),
        migrations.AlterField(
            model_name="mentatnewbie",
            name="newbie_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newbie",
                to="ddcz.UserProfile",
                db_column="newbie_id",
                db_constraint=False,
            ),
        ),
        migrations.RenameField("MentatNewbie", "newbie_id", "newbie"),
        migrations.RenameField("MentatNewbie", "mentat_id", "mentat"),
    ]
