# Generated by Django 2.0.13 on 2021-04-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0075_tavernaccess_django_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tavernaccess",
            name="id_stolu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.TavernTable",
                db_column="id_stolu",
            ),
        ),
    ]
