# Generated by Django 2.0.13 on 2021-05-05 12:48
import sys
from django.db import connection, migrations


def migrate_ignores(apps, schema_editor):
    TavernTableVisitor = apps.get_model("ddcz", "TavernTableVisitor")
    TavernTable = apps.get_model("ddcz", "TavernTable")
    UserProfile = apps.get_model("ddcz", "UserProfile")

    # Can't do IgnoredTavernTable.objects.raw() because primary keay / id was not migrated
    # not worth doing the manytomanyfield migration just for the purpose of this data migration
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_uz, id_stolu FROM `putyka_neoblibene`")
        row = cursor.fetchone()
        while row:
            id_uzivatele, id_stolu = row
            # We'll handle the ignores with ID 0 separately, after we discover WTAF
            # See https://github.com/dracidoupe/graveyard/issues/237#issuecomment-832671834
            if id_uzivatele > 0:
                try:
                    table_visitor = TavernTableVisitor.objects.get(
                        id_stolu=TavernTable(id=id_stolu),
                        id_uzivatele=UserProfile(id=id_uzivatele),
                    )
                except TavernTableVisitor.DoesNotExist:
                    table_visitor = TavernTableVisitor(
                        id_stolu=TavernTable(id=id_stolu),
                        id_uzivatele=UserProfile(id=id_uzivatele),
                    )

                table_visitor.oblibenost = -1
                try:
                    table_visitor.save()
                except ValueError as e:
                    sys.stderr.write(f"Can't save visitor {table_visitor}: {e}\n")
                    sys.stderr.flush()
                    raise

            row = cursor.fetchone()


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0081_taverntable_access_migration"),
    ]

    operations = [
        migrations.RunPython(migrate_ignores),
    ]
