# Generated by Django 2.0.13 on 2021-07-01 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0093_notice_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tavernaccess",
            old_name="user_nick",
            new_name="user_nick_or_id",
        ),
        migrations.AlterUniqueTogether(
            name="tavernaccess",
            unique_together={("tavern_table", "access_type", "user_nick_or_id")},
        ),
    ]
