# Generated by Django 2.0.13 on 2021-07-19 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0095_tavern-booleans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alchemisttool",
            options={
                "verbose_name": "Alchymistický předmět",
                "verbose_name_plural": "Alchimistické předměty",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Předmět", "verbose_name_plural": "Předměty"},
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"verbose_name": "Odkaz", "verbose_name_plural": "Odkazy"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Dovednost", "verbose_name_plural": "Dovednosti"},
        ),
        migrations.AlterModelOptions(
            name="wizardspell",
            options={
                "verbose_name": "Kouzelnické kouzlo",
                "verbose_name_plural": "Kouzelnická kouzla",
            },
        ),
    ]
