# Generated by Django 2.0.13 on 2021-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0105_auto_20210904_1146"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.CharField(max_length=150)),
                ("email_subject", models.CharField(max_length=255)),
                ("email_text", models.TextField()),
                ("sending_failures", models.IntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("NEWS_ADDED", "Nová aktualita")], max_length=255
                    ),
                ),
                ("serialized_model", models.TextField()),
                ("extra_data", models.TextField()),
                ("scheduled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
