# Generated by Django 2.0.13 on 2021-09-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0108_emaillist_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="email_uz",
            field=models.CharField(db_column="email_uz", max_length=40),
        ),
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="id_uz",
            field=models.IntegerField(
                db_column="id_uz", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="rubrika",
            field=models.CharField(db_column="rubrika", max_length=20),
        ),
    ]
