# Generated by Django 2.0.13 on 2021-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0113_emaillist_automagic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="django_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="user_profile_id",
            field=models.IntegerField(db_column="id_uz"),
        ),
    ]
