# Generated by Django 2.0.13 on 2021-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0114_emaillist_intfix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationemailsubscription",
            name="django_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
