# Generated by Django 2.0.13 on 2022-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0123_creationvote_automatic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationvote",
            name="django_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="creationvote",
            name="user_profile_id",
            field=models.IntegerField(db_column="id_uz"),
        ),
    ]
