# Generated by Django 2.0.13 on 2022-01-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0124_creationvote_nonnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationvote",
            name="django_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
