# Generated by Django 2.0.13 on 2022-01-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0126_creationvote_userprofile_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationvote",
            name="user_profile",
            field=models.ForeignKey(
                db_column="id_uz",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.UserProfile",
            ),
        ),
    ]
