version: '3.9'

services:

  web:
    build:
      context: .docker/web
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: /bin/bash -c "python3 manage.py runserver 0.0.0.0:8000"

  db:
    build:
      context: .docker/database
      dockerfile: Dockerfile
    volumes:
      - .docker/database/.db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=docker
      - MARIADB_DATABASE=dracidoupe_cz

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

