version: '3'

# This docker-compose is same as docker-compose.yml except it's not using
# volumes since they are not allowed under "docker" CircleCI environment
# See https://circleci.com/docs/2.0/executor-types/

services:

  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=ddcz
  web:
    environment:
      - SERVER_CI=true
    build:
      context: .docker/web
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
      - "32768-65535"
    depends_on:
      - db
      - chrome

  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
