CZECHOSLOVAK_REGIONS = [
    ("", "-- Vyberte kraj --"),
    ("Celá ČR", "Celá ČR"),
    ("Celá SR", "Celá SR"),
    # Czech Republic
    ("Praha", "Praha"),
    ("Středočeský", "Středočeský"),
    ("Jihočeský", "Jihočeský"),
    ("Plzeňský", "Plzeňský"),
    ("Karlovarský", "Karlovarský"),
    ("Ústecký", "Ústecký"),
    ("Liberecký", "Liberecký"),
    ("Královéhradecký", "Královéhradecký"),
    ("Pardubický", "Pardubický"),
    ("Vysočina", "Vysočina"),
    ("Jihomoravský", "Jihomoravský"),
    ("Olomoucký", "Olomoucký"),
    ("Zlínský", "Zlínský"),
    ("Moravskoslezský", "Moravskoslezský"),
    # Slovak Republic
    ("Bratislavský", "Bratislavský"),
    ("Trnavský", "Trnavský"),
    ("Trenčianský", "Trenčianský"),
    ("Nitrianský", "Nitrianský"),
    ("Žilinský", "Žilinský"),
    ("Banskobystrický", "Banskobystrický"),
    ("Prešovský", "Prešovský"),
    ("Košický", "Košický"),
]
