# Generated by Django 2.0.2 on 2018-06-08 20:28

import ddcz.models.magic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', ddcz.models.magic.MisencodedCharField(blank=True, max_length=40, null=True)),
                ('email', ddcz.models.magic.MisencodedCharField(blank=True, max_length=40, null=True)),
                ('telefon', ddcz.models.magic.MisencodedCharField(blank=True, max_length=20, null=True)),
                ('mobil', ddcz.models.magic.MisencodedCharField(blank=True, max_length=20, null=True)),
                ('vek', models.IntegerField(blank=True, null=True)),
                ('okres', ddcz.models.magic.MisencodedCharField(blank=True, max_length=40, null=True)),
                ('doba', ddcz.models.magic.MisencodedCharField(blank=True, max_length=20, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sekce', ddcz.models.magic.MisencodedCharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Seznamka',
                'verbose_name_plural': 'Seznamky',
                'db_table': 'seznamka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=20)),
                ('nick_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=25, unique=True)),
                ('prijmeni_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=20)),
                ('psw_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=40)),
                ('email_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=50)),
                ('pohlavi_uzivatele', ddcz.models.magic.MisencodedCharField(blank=True, max_length=4, null=True)),
                ('vek_uzivatele', models.IntegerField()),
                ('kraj_uzivatele', ddcz.models.magic.MisencodedCharField(max_length=20)),
                ('chat_barva', ddcz.models.magic.MisencodedCharField(max_length=6)),
                ('chat_pismo', models.IntegerField()),
                ('chat_reload', models.IntegerField()),
                ('chat_zprav', models.IntegerField()),
                ('chat_filtr', ddcz.models.magic.MisencodedCharField(blank=True, max_length=255, null=True)),
                ('chat_filtr_zobrazit', models.IntegerField()),
                ('pospristup', models.DateTimeField()),
                ('level', ddcz.models.magic.MisencodedCharField(max_length=1)),
                ('icq_uzivatele', models.IntegerField()),
                ('vypsat_udaje', ddcz.models.magic.MisencodedCharField(max_length=15)),
                ('ikonka_uzivatele', ddcz.models.magic.MisencodedCharField(blank=True, max_length=25, null=True)),
                ('popis_uzivatele', ddcz.models.magic.MisencodedCharField(blank=True, max_length=255, null=True)),
                ('nova_posta', models.IntegerField()),
                ('skin', ddcz.models.magic.MisencodedCharField(max_length=10)),
                ('reputace', models.IntegerField()),
                ('reputace_rozdel', models.PositiveIntegerField()),
                ('status', ddcz.models.magic.MisencodedCharField(max_length=1)),
                ('reg_schval_datum', models.DateTimeField(blank=True, null=True)),
                ('indexhodnotitele', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reload', ddcz.models.magic.MisencodedCharField(max_length=1)),
                ('max_level', models.IntegerField(blank=True, null=True)),
                ('api_key', ddcz.models.magic.MisencodedCharField(blank=True, max_length=40, null=True, unique=True)),
            ],
            options={
                'db_table': 'uzivatele',
                'managed': False,
            },
        ),
    ]
