# Generated by Django 2.0.2 on 2018-06-08 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0004_userprofile_user"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_user AUTO_INCREMENT=20000"
        )  # yup, hardcoded. Deal with it.
    ]
