# Generated by Django 2.0.2 on 2018-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0006_auto_20180609_1941"),
    ]

    operations = [
        migrations.RenameModel("LevelParametry2", "LevelSystemParams"),
    ]
