# Generated by Django 3.1.14 on 2024-12-29 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0006_dates_vol2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name="Přidáno"
            ),
            preserve_default=False,
        ),
    ]
