# Generated by Django 2.0.2 on 2018-06-10 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0007_levelsystemparams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hlasovaniprispevky",
            options={},
        ),
    ]
