# Generated by Django 2.0.2 on 2018-06-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0008_auto_20180610_2246"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HlasovaniPrispevky",
            new_name="CreationVotes",
        ),
        migrations.AlterUniqueTogether(
            name="creationvotes",
            unique_together={("id_uz", "id_cizi", "rubrika")},
        ),
    ]
