# Generated by Django 3.1.14 on 2024-12-30 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0008_more_market_room_20241230_0056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="published_varchar",
        ),
    ]
