# Generated by Django 3.1.14 on 2024-12-30 12:27

import ddcz.models.magic
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0009_remove_market_published_varchar"),
    ]

    operations = [
        migrations.AddField(
            model_name="dating",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="area",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="okres",
                max_length=40,
                null=True,
                verbose_name="Kraj",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="group",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[
                    ("hledam_hrace", "Hledám hráče"),
                    ("hledam_druzinu", "Hledám družinu"),
                    ("hledam_pj", "Hledám PJ"),
                    ("nabizim_druzinu", "Nabízím družinu"),
                    ("nabizim_pj", "Nabízím se jako PJ"),
                ],
                db_column="sekce",
                default="Hledám hráče",
                max_length=20,
                verbose_name="Sekce",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dating",
            name="name",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="jmeno", default="Anonym", max_length=40, verbose_name="Jméno"
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
            preserve_default=False,
        ),
    ]
