# Generated by Django 2.0.2 on 2018-06-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0010_creativepage_creativepageconcept_creativepagesection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestiar",
            options={},
        ),
    ]
