# Generated by Django 2.0.2 on 2018-06-13 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0011_auto_20180614_0018"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bestiar",
            new_name="Monster",
        ),
    ]
