# Generated by Django 3.1.14 on 2025-06-07 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0011_dating_autopublish_20250116_2222"),
        ("ddcz", "0003_lesschat"),
    ]

    operations = []
