# Generated by Django 3.1.14 on 2026-03-21 05:33

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0017_fix_awaiting_registration_pk_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloaditem",
            name="description",
            field=ddcz.models.magic.MisencodedTextField(db_column="popis"),
        ),
    ]
