# Generated by Django 2.0.2 on 2018-06-17 16:48

import ddcz.models.magic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0018_auto_20180617_1740'),
    ]

    operations = [
        migrations.RenameModel('Fotogalerie', 'Photo'),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterField(
            model_name='photo',
            name='autmail',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='autor',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cesta',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cestathumb',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='jmeno',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pochvez',
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='schvaleno',
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zdroj',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zdrojmail',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='hodnota_hlasovani',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pocet_hlasujicich',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='precteno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='tisknuto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='autmail',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='autor',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='schvaleno',
            field=ddcz.models.magic.MisencodedCharField(choices=[('a', 'Schváleno'), ('n', 'Neschváleno')], max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zdrojmail',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pochvez',
            field=ddcz.models.magic.MisencodedIntegerField(max_length=5),
        ),
    ]
