# Generated by Django 2.0.13 on 2020-03-04 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0021_commonarticle_attr_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelsystemparams",
            options={},
        ),
    ]
