# Generated by Django 2.0.13 on 2020-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0023_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dovednosti',
            new_name='Skill',
        ),
    ]
