# Generated by Django 2.0.13 on 2020-10-10 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0025_properencodingscatchup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linky",
            options={},
        ),
    ]
