# Generated by Django 2.0.13 on 2020-10-11 19:02

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0027_links_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='adresa',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='nazev',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='pochvez',
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='popis',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='schvaleno',
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
    ]
