# Generated by Django 2.0.13 on 2020-10-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0029_alchemist_tools"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alchpredmety",
            new_name="AlchemistTools",
        ),
    ]
