# Generated by Django 2.0.13 on 2020-10-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0030_alchemist_tools_rename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AlchemistTools",
            new_name="AlchemistTool",
        ),
    ]
