# Generated by Django 2.0.13 on 2020-10-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0033_ranger_spell"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hranicarkouzla",
            new_name="RangerSpell",
        ),
    ]
