# Generated by Django 2.0.13 on 2020-10-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0040_download"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Downloady",
            new_name="DownloadItem",
        ),
    ]
