# Generated by Django 2.0.13 on 2020-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0042_download_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloaditem",
            name="item",
            field=models.FileField(null=True, upload_to="soub"),
        ),
    ]
