# Generated by Django 2.0.13 on 2020-11-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("ddcz", "0048_author"),
        ("ddcz", "0049_author_rename"),
        ("ddcz", "0050_author_anonymous"),
    ]

    dependencies = [
        ("ddcz", "0047_quests_rename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("u", "Uživatel"),
                            ("w", "Webová Stránka"),
                            ("a", "Anonymní Uživatel"),
                        ],
                        default=None,
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddcz.UserProfile",
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "website_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anonymous_user_nick",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alchemisttool",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="commonarticle",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="downloaditem",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="gallerypicture",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="rangerspell",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
        migrations.AddField(
            model_name="wizardspell",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.Author",
            ),
        ),
    ]
