# Generated by Django 2.0.13 on 2020-11-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0049_forum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Phorum',
        ),
    ]
