# Generated by Django 2.0.13 on 2020-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0050_phorum_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="user_nick",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
