# Generated by Django 2.0.13 on 2021-04-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0054_diskuze"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Diskuze",
            new_name="CreationComment",
        ),
    ]
