# Generated by Django 2.0.13 on 2021-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0056_creationcomments_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="creationcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.UserProfile",
            ),
        ),
    ]
