# Generated by Django 2.0.13 on 2021-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0057_creationcomment_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Jméno")),
                ("slug", models.CharField(max_length=40, unique=True)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "Redakční článek",
                "verbose_name_plural": "Redakční články",
            },
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="datum",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
