# Generated by Django 2.0.13 on 2021-04-15 14:06

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0059_sm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inzerce",
            options={},
        ),
        migrations.AlterField(
            model_name="dating",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="datum",
            field=ddcz.models.magic.MisencodedCharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="jmeno",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="mail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="mobil",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="okres",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="sekce",
            field=ddcz.models.magic.MisencodedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="telefon",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inzerce",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(),
        ),
    ]
