# Generated by Django 2.0.13 on 2021-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0060_inzerce"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inzerce",
            new_name="Market",
        ),
        migrations.AlterModelOptions(
            name="market",
            options={"verbose_name": "Inzerce", "verbose_name_plural": "Inzerce"},
        ),
    ]
