# Generated by Django 2.0.13 on 2021-04-16 16:01

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0061_market"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentatnewbie",
            options={},
        ),
        migrations.AlterField(
            model_name="market",
            name="sekce",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[
                    ("nabizim", "Nabízím"),
                    ("shanim", "Sháním"),
                    ("vymenim", "Vyměním"),
                    ("daruji", "Daruji"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mentatnewbie",
            name="locked",
            field=ddcz.models.magic.MisencodedCharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name="mentatnewbie",
            unique_together={("newbie_id", "mentat_id")},
        ),
    ]
