# Generated by Django 2.0.13 on 2021-04-18 23:10

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0061_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='sekce',
            field=ddcz.models.magic.MisencodedCharField(choices=[('nabizim', 'Nabízím'), ('shanim', 'Sháním'), ('vymenim', 'Vyměním'), ('daruji', 'Daruji')], max_length=20),
        ),
    ]
