# Generated by Django 2.0.13 on 2021-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0067_field_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentatnewbie",
            name="django_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
