# Generated by Django 2.0.13 on 2021-04-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0069_mentat_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentatnewbie",
            name="mentat",
            field=models.ForeignKey(
                db_column="mentat_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentats",
                to="ddcz.UserProfile",
            ),
        ),
        migrations.AlterField(
            model_name="mentatnewbie",
            name="newbie",
            field=models.ForeignKey(
                db_column="newbie_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newbies",
                to="ddcz.UserProfile",
            ),
        ),
    ]
