# Generated by Django 2.0.13 on 2021-04-28 11:08

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0070_mentat_plural"),
    ]

    operations = [
        # This may create user issues, but it's only 7 records
        migrations.RunSQL(
            sql=[
                (
                    """
            DELETE FROM
                `putyka_uzivatele`
            WHERE
                navstiveno < "2000-01-01 01:01"
            """
                )
            ],
            reverse_sql=[],
        ),
        migrations.AlterModelOptions(
            name="putykabook",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykalinky",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykanastenky",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykanavstevnost",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykaneoblibene",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="putykaprispevky",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykapristup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykasekce",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykaslucovani",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykastoly",
            options={},
        ),
        migrations.AlterModelOptions(
            name="putykauzivatele",
            options={},
        ),
        migrations.AlterField(
            model_name="putykanastenky",
            name="nazev_stolu",
            field=ddcz.models.magic.MisencodedCharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="putykanastenky",
            name="text_nastenky",
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name="putykanastenky",
            name="zmenil",
            field=ddcz.models.magic.MisencodedCharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="putykanavstevnost",
            name="misto",
            field=ddcz.models.magic.MisencodedCharField(max_length=31),
        ),
        migrations.AlterField(
            model_name="putykaprispevky",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="putykaprispevky",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name="putykapristup",
            name="nick_usera",
            field=ddcz.models.magic.MisencodedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="putykapristup",
            name="typ_pristupu",
            field=ddcz.models.magic.MisencodedCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="putykasekce",
            name="nazev",
            field=ddcz.models.magic.MisencodedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="putykasekce",
            name="popis",
            field=ddcz.models.magic.MisencodedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="putykaslucovani",
            name="oznaceni",
            field=ddcz.models.magic.MisencodedCharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="jmeno",
            field=ddcz.models.magic.MisencodedCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="min_level",
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="popis",
            field=ddcz.models.magic.MisencodedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="povol_hodnoceni",
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="verejny",
            field=ddcz.models.magic.MisencodedCharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="putykastoly",
            name="vlastnik",
            field=ddcz.models.magic.MisencodedCharField(max_length=30),
        ),
    ]
