# Generated by Django 2.0.13 on 2021-04-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0073_tavernbookmark_django_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tavern_bookmarks',
            field=models.ManyToManyField(through='ddcz.TavernBookmark', to='ddcz.TavernTable'),
        ),
        migrations.AlterField(
            model_name='tavernbookmark',
            name='id_stolu',
            field=models.ForeignKey(db_column='id_stolu', on_delete=django.db.models.deletion.CASCADE, to='ddcz.TavernTable'),
        ),
        migrations.AlterField(
            model_name='tavernbookmark',
            name='id_uz',
            field=models.ForeignKey(db_column='id_uz', on_delete=django.db.models.deletion.CASCADE, to='ddcz.UserProfile'),
        ),
    ]
