# Generated by Django 2.0.13 on 2021-04-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0076_tavern_access_fk"),
    ]

    operations = [
        # One record, but it blocks any modifications
        migrations.RunSQL(
            sql=[
                (
                    """
                        DELETE FROM
                            `putyka_prispevky`
                        WHERE
                            `datum` < "2000-01-01 01:01"
                    """
                )
            ],
            reverse_sql=[],
        ),
        # This is needed in order to get rid of default "0000-00-00 00:00:00" values
        migrations.RunSQL(
            sql=[
                (
                    """
                        ALTER TABLE
                            `putyka_prispevky`
                        MODIFY
                            `datum` DATETIME NOT NULL;
                    """
                )
            ],
            reverse_sql=[],
        ),
        migrations.AlterField(
            model_name="taverncomment",
            name="id_stolu",
            field=models.ForeignKey(
                db_column="id_stolu",
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.TavernTable",
            ),
        ),
    ]
