# Generated by Django 2.0.13 on 2021-05-03 13:33

from django.db import migrations, models


def fill_relation_table_ids(apps, schema_editor):
    Relation = apps.get_model("ddcz", "TavernTableVisitor")
    i = 1
    for relation in Relation.objects.all():
        Relation.objects.filter(
            id_stolu=relation.id_stolu, id_uzivatele=relation.id_uzivatele
        ).update(django_id=i)
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0077_tavern_comment_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="taverntablevisitor",
            name="django_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(fill_relation_table_ids),
        migrations.RunSQL("ALTER TABLE `putyka_uzivatele` DROP PRIMARY KEY;"),
        migrations.RunSQL(
            "ALTER TABLE putyka_uzivatele MODIFY django_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY;"
        ),
        migrations.RunSQL(
            """
                SET @m = (SELECT IFNULL(MAX(django_id) + 1, 1) FROM putyka_uzivatele);
                SET @s = CONCAT('ALTER TABLE putyka_uzivatele AUTO_INCREMENT=', @m);
                PREPARE stmt1 FROM @s;
                EXECUTE stmt1;
                DEALLOCATE PREPARE stmt1;
            """
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="django_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="id_stolu",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="django_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
