# Generated by Django 2.0.13 on 2021-05-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0078_taverntablevisitor_django_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="id_stolu",
            field=models.ForeignKey(
                db_column="id_stolu",
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.TavernTable",
            ),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="id_uzivatele",
            field=models.ForeignKey(
                db_column="id_uz",
                on_delete=django.db.models.deletion.CASCADE,
                to="ddcz.UserProfile",
            ),
        ),
    ]
