# Generated by Django 2.0.13 on 2021-05-05 12:32

from django.db import migrations
from ddcz.tavern import migrate_tavern_access


def migrate_access(apps, schema_editor):
    table_visitor_model = apps.get_model("ddcz", "TavernTableVisitor")
    tavern_access_model = apps.get_model("ddcz", "TavernAccess")
    user_profile_model = apps.get_model("ddcz", "UserProfile")
    # Because of our model rename migration, we would have to have a frozen copy of
    # the function here. Given the production is migrated, let's mark it as noop now
    # migrate_tavern_access(
    #     print_progress=True,
    #     table_visitor_model=table_visitor_model,
    #     tavern_access_model=tavern_access_model,
    #     user_profile_model=user_profile_model,
    # )


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0080_taverntable_defaults"),
    ]

    operations = [
        migrations.RunPython(migrate_access),
    ]
