# Generated by Django 2.0.13 on 2021-05-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0082_taverntable_ingores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uzivatelecekajici",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="uzivatelecekajici",
            unique_together={("jmeno", "prijmeni")},
        ),
    ]
