# Generated by Django 2.0.13 on 2021-06-09 15:45

import ddcz.models.magic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0083_user_waiting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="inteligence",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="inteligence",
                max_length=50,
                null=True,
                verbose_name="Inteligence",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_filtr",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="chat_filtr", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="bcz",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="bcz",
                max_length=30,
                null=True,
                verbose_name="Barva/chuť/zápach:",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="denmag",
            field=models.IntegerField(
                blank=True, db_column="denmag", null=True, verbose_name="Magy/den"
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="dosah_ucinku",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="dosah_ucinku",
                max_length=20,
                null=True,
                verbose_name="Dosah účinku",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="mag",
            field=models.IntegerField(
                blank=True, db_column="mag", null=True, verbose_name="Magenergie"
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="nalezeni",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="nalezeni",
                max_length=150,
                null=True,
                verbose_name="Nalezení",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="nebezpecnost",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="nebezpecnost",
                max_length=30,
                null=True,
                verbose_name="Nebezpečnost",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="popis", verbose_name="Popis"
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="sfera",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="sfera",
                max_length=20,
                null=True,
                verbose_name="Sféra",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="sila",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="sila",
                max_length=30,
                null=True,
                verbose_name="Síla",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="skupina",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="skupina", max_length=30, verbose_name="Skupina"
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="suroviny",
            field=models.SmallIntegerField(
                blank=True, db_column="suroviny", null=True, verbose_name="Suroviny"
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="trvani",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="trvani",
                max_length=30,
                null=True,
                verbose_name="Trvání",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="uroven_vyrobce",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="uroven_vyrobce",
                max_length=10,
                null=True,
                verbose_name="Úroveň výrobce",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="vyroba",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="vyroba",
                max_length=30,
                null=True,
                verbose_name="Výroba",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="zaklad",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="zaklad",
                max_length=150,
                null=True,
                verbose_name="Základ",
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="alchemisttool",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="anotace",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="anotace", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="rubrika",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="rubrika", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="skupina",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="skupina", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="commonarticle",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="cizi_tbl",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="cizi_tbl", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="email",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="email", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="id_cizi",
            field=models.IntegerField(db_column="id_cizi"),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="nickname",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nickname", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="reputace",
            field=models.IntegerField(db_column="reputace"),
        ),
        migrations.AlterField(
            model_name="creationcomment",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="id_cizi",
            field=models.IntegerField(db_column="id_cizi"),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="id_uz",
            field=models.IntegerField(
                db_column="id_uz", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="opraveno",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="opraveno", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="pochvez",
            field=models.IntegerField(db_column="pochvez"),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="rubrika",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="rubrika", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="creationvotes",
            name="time",
            field=models.IntegerField(db_column="time"),
        ),
        migrations.AlterField(
            model_name="dating",
            name="datum",
            field=models.DateTimeField(
                blank=True, db_column="datum", null=True, verbose_name="Datum"
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="doba",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="doba",
                max_length=20,
                null=True,
                verbose_name="Doba hraní DrD",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="jmeno",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="jmeno",
                max_length=40,
                null=True,
                verbose_name="Jméno",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="mobil",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="mobil",
                max_length=20,
                null=True,
                verbose_name="Mobil",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="okres",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="okres",
                max_length=40,
                null=True,
                verbose_name="Okres",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="sekce",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="sekce",
                max_length=20,
                null=True,
                verbose_name="Sekce",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="telefon",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="telefon",
                max_length=20,
                null=True,
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="text", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="vek",
            field=models.IntegerField(
                blank=True, db_column="vek", null=True, verbose_name="Věk"
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="cesta",
            field=models.TextField(blank=True, db_column="cesta", null=True),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="download_counter",
            field=models.IntegerField(db_column="download_counter", default=0),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="format",
            field=models.TextField(db_column="format"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="item",
            field=models.FileField(db_column="item", null=True, upload_to="soub"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="popis",
            field=models.TextField(db_column="popis"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="skupina",
            field=models.TextField(db_column="skupina"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="velikost",
            field=models.IntegerField(db_column="velikost"),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="cesta",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="cesta", verbose_name="Cesta k obrázku"
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="cestathumb",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="cestathumb", verbose_name="Cesta k náhledovému obrázku"
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gallerypicture",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cena",
            field=models.IntegerField(db_column="cena", verbose_name="Cena"),
        ),
        migrations.AlterField(
            model_name="item",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="item",
            name="delka",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="delka",
                max_length=3,
                null=True,
                verbose_name="Délka",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="item",
            name="kz",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="KZ",
                max_length=3,
                null=True,
                verbose_name="Kvalita zbroje",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="malydostrel",
            field=models.IntegerField(
                blank=True,
                db_column="malydostrel",
                null=True,
                verbose_name="Malý dostřel",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="popis", verbose_name="Popis"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sfera",
            field=models.IntegerField(
                blank=True, db_column="sfera", null=True, verbose_name="Sféra"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="skupina",
            field=ddcz.models.magic.MisencodedTextField(db_column="skupina"),
        ),
        migrations.AlterField(
            model_name="item",
            name="strednidostrel",
            field=models.IntegerField(
                blank=True,
                db_column="strednidostrel",
                null=True,
                verbose_name="Střední dostřel",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="uc",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="UC", null=True, verbose_name="Síla zbraně"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="vaha",
            field=models.IntegerField(db_column="vaha", verbose_name="Váha"),
        ),
        migrations.AlterField(
            model_name="item",
            name="velkydostrel",
            field=models.IntegerField(
                blank=True,
                db_column="velkydostrel",
                null=True,
                verbose_name="Velký dostřel",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="levelsystemparams",
            name="hodnota",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="hodnota", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="levelsystemparams",
            name="parametr",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="parametr", max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="adresa",
            field=ddcz.models.magic.MisencodedTextField(db_column="adresa"),
        ),
        migrations.AlterField(
            model_name="link",
            name="datum",
            field=models.DateTimeField(db_column="datum"),
        ),
        migrations.AlterField(
            model_name="link",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="nazev",
            field=ddcz.models.magic.MisencodedTextField(db_column="nazev"),
        ),
        migrations.AlterField(
            model_name="link",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="pochvez",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="pochvez", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(db_column="popis"),
        ),
        migrations.AlterField(
            model_name="link",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="datum",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="datum", max_length=12, verbose_name="Přidáno"
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="jmeno",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="jmeno",
                max_length=30,
                null=True,
                verbose_name="Jméno",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="mail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="mail",
                max_length=30,
                null=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="mobil",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="mobil",
                max_length=15,
                null=True,
                verbose_name="Mobil",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="okres",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="okres",
                max_length=20,
                null=True,
                verbose_name="Okres",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="sekce",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[
                    ("nabizim", "Nabízím"),
                    ("shanim", "Sháním"),
                    ("vymenim", "Vyměním"),
                    ("daruji", "Daruji"),
                ],
                db_column="sekce",
                max_length=20,
                verbose_name="Sekce",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="telefon",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="telefon",
                max_length=15,
                null=True,
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="monster",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="bojovnost",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="bojovnost",
                max_length=50,
                null=True,
                verbose_name="Bojovnost",
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="monster",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="monster",
            name="oc",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="oc", verbose_name="Obranné číslo"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="odl",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="odl", max_length=3, verbose_name="Odolnost"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="poh",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="poh", null=True, verbose_name="Pohyblivost"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="pokl",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="pokl", null=True, verbose_name="Poklady"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="popis", verbose_name="Popis"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="monster",
            name="pres",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="pres", null=True, verbose_name="Přesvědčení"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="skupina",
            field=ddcz.models.magic.MisencodedTextField(db_column="skupina"),
        ),
        migrations.AlterField(
            model_name="monster",
            name="sm",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True,
                db_column="SM",
                max_length=50,
                null=True,
                verbose_name="Síla mysli",
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="monster",
            name="uc",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="uc", verbose_name="Útočné číslo"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="vel",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="vel", max_length=20, verbose_name="Velikost"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="zkus",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="zkus", max_length=50, verbose_name="Zkušenost"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="zran",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zran", null=True, verbose_name="Zranitelnost"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="zvt",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="zvt", verbose_name="Životaschopnost"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="autmail",
            field=ddcz.models.magic.MisencodedTextField(db_column="autmail"),
        ),
        migrations.AlterField(
            model_name="news",
            name="autor",
            field=ddcz.models.magic.MisencodedTextField(db_column="autor"),
        ),
        migrations.AlterField(
            model_name="news",
            name="datum",
            field=models.DateTimeField(db_column="datum"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="email",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="email", null=True
            ),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="nickname",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nickname", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="reg",
            field=ddcz.models.magic.MisencodedCharField(db_column="reg", max_length=50),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="reputace",
            field=models.IntegerField(db_column="reputace"),
        ),
        migrations.AlterField(
            model_name="phorum",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="cesta",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="cesta", verbose_name="Cesta k obrázku"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="cestathumb",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="cestathumb", verbose_name="Cesta k náhledovému obrázku"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="photo",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="photo",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="anotace",
            field=models.TextField(db_column="anotace"),
        ),
        migrations.AlterField(
            model_name="quest",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="cesta",
            field=models.TextField(blank=True, db_column="cesta", null=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="quest",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="quest",
            name="klicsl",
            field=models.TextField(db_column="klicsl"),
        ),
        migrations.AlterField(
            model_name="quest",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="quest",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="quest",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="cetnost",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="cetnost", null=True, verbose_name="Četnost"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="dosah",
            field=models.SmallIntegerField(
                blank=True, db_column="dosah", null=True, verbose_name="Rozsah"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="dosahpop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="dosahpop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="druh",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="druh", null=True, verbose_name="Druh"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="mag",
            field=models.SmallIntegerField(db_column="mag", verbose_name="Magenergie"),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="magpop",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="magpop", verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="pomucky",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="pomucky", null=True, verbose_name="Pomůcky"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="popis", verbose_name="Popis"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="rozsah",
            field=models.SmallIntegerField(
                blank=True, db_column="rozsah", null=True, verbose_name="Rozsah"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="rozsahpop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="rozsahpop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="skupina",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="skupina", verbose_name="Skupina"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="vyvolani",
            field=models.SmallIntegerField(
                blank=True, db_column="vyvolani", null=True, verbose_name="Vyvolání"
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="vyvolanipop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="vyvolanipop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rangerspell",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="fatneuspech",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="fatneuspech", verbose_name="Fatální neúspěch"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="hlasoval",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="hlasoval", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="neuspech",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="neuspech", verbose_name="Neúspěch"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="obtiznost",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="obtiznost", verbose_name="Obtížnost"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="overovani",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="overovani", verbose_name="Ověřování"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="popis", verbose_name="Popis"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="skill",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skupina",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="skupina", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="skill",
            name="totuspech",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="totuspech", verbose_name="Totální úspěch"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="uspech",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="uspech", verbose_name="Úspěch"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="vlastnost",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="vlastnost", verbose_name="Vlastnost"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tavernaccess",
            name="nick_usera",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nick_usera", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="tavernaccess",
            name="typ_pristupu",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="typ_pristupu", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="taverncomment",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="autor", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="taverncomment",
            name="datum",
            field=models.DateTimeField(db_column="datum"),
        ),
        migrations.AlterField(
            model_name="taverncomment",
            name="reputace",
            field=models.IntegerField(db_column="reputace"),
        ),
        migrations.AlterField(
            model_name="taverncomment",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="text"),
        ),
        migrations.AlterField(
            model_name="tavernsection",
            name="kod",
            field=models.IntegerField(db_column="kod"),
        ),
        migrations.AlterField(
            model_name="tavernsection",
            name="nazev",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nazev", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tavernsection",
            name="popis",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="popis", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="tavernsection",
            name="poradi",
            field=models.IntegerField(db_column="poradi"),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="celkem",
            field=models.IntegerField(blank=True, db_column="celkem", null=True),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="jmeno",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="jmeno", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="min_level",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="min_level", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="popis",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="popis", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="povol_hodnoceni",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="povol_hodnoceni", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="sekce",
            field=models.IntegerField(db_column="sekce"),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="verejny",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="verejny", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="vlastnik",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="vlastnik", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="zalozen",
            field=models.DateTimeField(db_column="zalozen"),
        ),
        migrations.AlterField(
            model_name="taverntablelink",
            name="id_linku",
            field=models.IntegerField(db_column="id_linku"),
        ),
        migrations.AlterField(
            model_name="taverntablelink",
            name="id_stolu",
            field=models.IntegerField(
                db_column="id_stolu", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="taverntablemerge",
            name="id_ja",
            field=models.IntegerField(db_column="id_ja"),
        ),
        migrations.AlterField(
            model_name="taverntablemerge",
            name="id_on",
            field=models.IntegerField(db_column="id_on"),
        ),
        migrations.AlterField(
            model_name="taverntablemerge",
            name="oznaceni",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="oznaceni", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="taverntablemerge",
            name="zustavam",
            field=models.SmallIntegerField(db_column="zustavam"),
        ),
        migrations.AlterField(
            model_name="taverntablenoticeboard",
            name="id_stolu",
            field=models.IntegerField(db_column="id_stolu", unique=True),
        ),
        migrations.AlterField(
            model_name="taverntablenoticeboard",
            name="nazev_stolu",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nazev_stolu", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="taverntablenoticeboard",
            name="posledni_zmena",
            field=models.DateTimeField(
                blank=True, db_column="posledni_zmena", null=True
            ),
        ),
        migrations.AlterField(
            model_name="taverntablenoticeboard",
            name="text_nastenky",
            field=ddcz.models.magic.MisencodedTextField(db_column="text_nastenky"),
        ),
        migrations.AlterField(
            model_name="taverntablenoticeboard",
            name="zmenil",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="zmenil", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="navstiveno",
            field=models.DateTimeField(blank=True, db_column="navstiveno", null=True),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="neprectenych",
            field=models.IntegerField(blank=True, db_column="neprectenych", null=True),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="oblibenost",
            field=models.IntegerField(db_column="oblibenost", default=0),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="pristup",
            field=models.IntegerField(db_column="pristup", default=0),
        ),
        migrations.AlterField(
            model_name="taverntablevisitor",
            name="sprava",
            field=models.IntegerField(db_column="sprava", default=0),
        ),
        migrations.AlterField(
            model_name="tavernvisit",
            name="cas",
            field=models.DateTimeField(
                db_column="cas", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tavernvisit",
            name="misto",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="misto", max_length=31
            ),
        ),
        migrations.AlterField(
            model_name="tavernvisit",
            name="pocet",
            field=models.IntegerField(db_column="pocet"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_barva",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="chat_barva", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_filtr_zobrazit",
            field=models.IntegerField(db_column="chat_filtr_zobrazit", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_pismo",
            field=models.IntegerField(db_column="chat_pismo", default=12),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_reload",
            field=models.IntegerField(db_column="chat_reload", default=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat_zprav",
            field=models.IntegerField(db_column="chat_zprav", default=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="email_uzivatele", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="icq_uzivatele",
            field=models.IntegerField(db_column="icq_uzivatele", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ikonka_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="ikonka_uzivatele", max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="indexhodnotitele",
            field=models.DecimalField(
                db_column="indexhodnotitele",
                decimal_places=2,
                default=-99.99,
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="jmeno_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="jmeno_uzivatele", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="kraj_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="kraj_uzivatele", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="level", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_level",
            field=models.IntegerField(blank=True, db_column="max_level", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nick_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nick_uzivatele", max_length=25, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nova_posta",
            field=models.IntegerField(db_column="nova_posta", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pohlavi_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="pohlavi_uzivatele", max_length=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="popis_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="popis_uzivatele", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pospristup",
            field=models.DateTimeField(db_column="pospristup"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="prijmeni_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="prijmeni_uzivatele", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="psw_uzivatele",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="psw_uzivatele", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reg_schval_datum",
            field=models.DateTimeField(
                auto_now_add=True, db_column="reg_schval_datum", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reload",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="reload", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reputace",
            field=models.IntegerField(db_column="reputace", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reputace_rozdel",
            field=models.PositiveIntegerField(db_column="reputace_rozdel", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skin",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="skin", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="status", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vek_uzivatele",
            field=models.IntegerField(db_column="vek_uzivatele", default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vypsat_udaje",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="vypsat_udaje", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="datum",
            field=models.IntegerField(db_column="datum"),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="email",
            field=models.CharField(db_column="email", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="id_zaznamu",
            field=models.AutoField(
                db_column="id_zaznamu", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="jmeno",
            field=models.CharField(db_column="jmeno", max_length=40),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="nick_uzivatele",
            field=models.CharField(
                db_column="nick_uzivatele", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="osloveni",
            field=models.CharField(
                blank=True, db_column="osloveni", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="patron",
            field=models.IntegerField(db_column="patron"),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="pohlavi",
            field=models.CharField(db_column="pohlavi", max_length=4),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="popis_text",
            field=models.TextField(db_column="popis_text"),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="prijmeni",
            field=models.CharField(db_column="prijmeni", max_length=40),
        ),
        migrations.AlterField(
            model_name="uzivatelecekajici",
            name="primluvy",
            field=models.IntegerField(db_column="primluvy"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="autmail",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autmail", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="autor",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="autor", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="datum",
            field=models.DateTimeField(auto_now_add=True, db_column="datum"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="dosah",
            field=models.IntegerField(
                blank=True, db_column="dosah", null=True, verbose_name="Rozsah"
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="dosahpop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="dosahpop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="hodnota_hlasovani",
            field=models.IntegerField(
                blank=True, db_column="hodnota_hlasovani", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="jmeno",
            field=ddcz.models.magic.MisencodedTextField(db_column="jmeno"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="kouzsl",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="kouzsl", verbose_name="Kouzelná slova"
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="mag",
            field=models.SmallIntegerField(db_column="mag", verbose_name="Magenergie"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="magpop",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="magpop", verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="past",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="past", null=True, verbose_name="Past"
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="pocet_hlasujicich",
            field=models.IntegerField(
                blank=True, db_column="pocet_hlasujicich", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="pochvez",
            field=ddcz.models.magic.MisencodedIntegerField(
                db_column="pochvez", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="popis",
            field=ddcz.models.magic.MisencodedTextField(db_column="popis"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="precteno",
            field=models.IntegerField(db_column="precteno", default=0),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="rozsah",
            field=models.SmallIntegerField(
                blank=True, db_column="rozsah", null=True, verbose_name="Rozsah"
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="rozsahpop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="rozsahpop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="schvaleno",
            field=ddcz.models.magic.MisencodedCharField(
                choices=[("a", "Schváleno"), ("n", "Neschváleno")],
                db_column="schvaleno",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="skupina",
            field=ddcz.models.magic.MisencodedTextField(db_column="skupina"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="tisknuto",
            field=models.IntegerField(db_column="tisknuto", default=0),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="trvani",
            field=models.IntegerField(db_column="trvani", verbose_name="Trvání"),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="trvanipop",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="trvanipop", null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="vyvolani",
            field=models.SmallIntegerField(
                db_column="vyvolani", verbose_name="Vyvolání"
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="vyvolanipop",
            field=ddcz.models.magic.MisencodedTextField(
                db_column="vyvolanipop", verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="zdroj",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdroj", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wizardspell",
            name="zdrojmail",
            field=ddcz.models.magic.MisencodedTextField(
                blank=True, db_column="zdrojmail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pospristup",
            field=models.DateTimeField(auto_now_add=True, db_column="pospristup"),
        ),
        migrations.AlterUniqueTogether(
            name="taverntablevisitor",
            unique_together={("id_stolu", "id_uzivatele")},
        ),
    ]
