# Generated by Django 2.0.13 on 2021-06-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0089_reputation_db_columns_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reputationadditional",
            old_name="hodnota",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="reputationadditional",
            old_name="prijal_nick",
            new_name="donee",
        ),
        migrations.RenameField(
            model_name="reputationadditional",
            old_name="duvod_udeleni",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="reputationlog",
            old_name="akce",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="reputationlog",
            old_name="v_diskusi",
            new_name="discussion",
        ),
        migrations.RenameField(
            model_name="reputationlog",
            old_name="prijal",
            new_name="donee",
        ),
        migrations.RenameField(
            model_name="reputationlog",
            old_name="dal",
            new_name="donor",
        ),
        migrations.RenameField(
            model_name="reputationlog",
            old_name="id_prispevku",
            new_name="post",
        ),
    ]
