# Generated by Django 2.0.13 on 2021-06-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0090_prune_lost_tavern_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tavernpost",
            old_name="author",
            new_name="author_nick",
        ),
        migrations.AddField(
            model_name="tavernpost",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddcz.UserProfile",
            ),
        ),
    ]
