# Generated by Django 2.0.13 on 2021-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0096_fix-plulars"),
    ]

    operations = [
        # Manually adjust for invalid default `0000-00-00 00:00:00`
        migrations.RunSQL(
            sql=[
                (
                    """
            ALTER TABLE
                `putyka_stoly`
            ALTER COLUMN
                `zalozen`
            DROP DEFAULT;
            """
                )
            ],
            reverse_sql=[],
        ),
        migrations.AlterField(
            model_name="taverntable",
            name="posts_no",
            field=models.IntegerField(db_column="celkem", default=0),
        ),
    ]
