# Generated by Django 2.0.13 on 2021-07-25 11:19

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0099_fix_reputation_typo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reputationadditional",
            name="donee",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="prijal_nick", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="reputationadditional",
            name="reason",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="duvod_udeleni", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="reputationlog",
            name="action",
            field=ddcz.models.magic.MisencodedCharField(db_column="akce", max_length=3),
        ),
        migrations.AlterField(
            model_name="reputationlog",
            name="discussion",
            field=ddcz.models.magic.MisencodedCharField(
                blank=True, db_column="v_diskusi", max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reputationlog",
            name="donee",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="prijal", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="reputationlog",
            name="donor",
            field=ddcz.models.magic.MisencodedCharField(db_column="dal", max_length=30),
        ),
    ]
