# Generated by Django 2.0.13 on 2021-07-26 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0100_fix_reputation_encoding"),
    ]

    # This is to compensate for a bad migration from <https://github.com/dracidoupe/graveyard/pull/301>
    # See <https://github.com/dracidoupe/graveyard/issues/309>
    if settings.DATABASE_IS_SEEDED:
        operations = [
            migrations.RemoveField(
                model_name="taverntablenoticeboard",
                name="id",
            ),
        ]
    else:
        operations = []
