# Generated by Django 2.0.13 on 2021-08-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0102_letters_of_postal_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letters',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='prijemce',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='odesilatel',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='viditelnost',
            new_name='visibility',
        ),
    ]
