# Generated by Django 2.0.13 on 2021-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0103_letters_col_rename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runy",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userratings",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="userratings",
            unique_together={("byfk", "forfk")},
        ),
        migrations.RenameField(
            model_name="userratings",
            old_name="byfk",
            new_name="by_id",
        ),
        migrations.RenameField(
            model_name="userratings",
            old_name="forfk",
            new_name="for_id",
        ),
        migrations.AlterField(
            model_name="runy",
            name="datum",
            field=models.DateTimeField(db_column="datum"),
        ),
        migrations.AlterField(
            model_name="runy",
            name="grafika",
            field=models.SmallIntegerField(db_column="grafika"),
        ),
        migrations.AlterField(
            model_name="runy",
            name="id_darce",
            field=models.IntegerField(db_column="id_darce"),
        ),
        migrations.AlterField(
            model_name="runy",
            name="id_prijemce",
            field=models.IntegerField(blank=True, db_column="id_prijemce", null=True),
        ),
        migrations.AlterField(
            model_name="runy",
            name="nick_darce",
            field=models.CharField(db_column="nick_darce", max_length=30),
        ),
        migrations.AlterField(
            model_name="runy",
            name="nick_prijemce",
            field=models.CharField(db_column="nick_prijemce", max_length=30),
        ),
        migrations.AlterField(
            model_name="runy",
            name="typ",
            field=models.CharField(db_column="typ", max_length=15),
        ),
        migrations.AlterField(
            model_name="runy",
            name="venovani",
            field=models.TextField(db_column="venovani"),
        ),
        migrations.AlterUniqueTogether(
            name="userratings",
            unique_together={("by_id", "for_id")},
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="datum",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="id_darce",
            new_name="donor_id",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="nick_darce",
            new_name="donor_nick",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="grafika",
            new_name="graphics",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="id_prijemce",
            new_name="receiver_id",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="nick_prijemce",
            new_name="receiver_nick",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="venovani",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="runy",
            old_name="typ",
            new_name="type",
        ),
        migrations.RenameModel(
            old_name="Runy",
            new_name="Runes",
        ),
    ]
