# Generated by Django 2.0.13 on 2021-09-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0106_scheduledemail_schedulednotification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uzivatelemaillist",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="uzivatelemaillist",
            unique_together={("id_uz", "rubrika")},
        ),
    ]
