# Generated by Django 2.0.13 on 2021-09-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0107_emaillist_intro"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UzivateleMaillist",
            new_name="CreationEmailSubscription",
        ),
    ]
