# Generated by Django 2.0.13 on 2021-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0110_emaillist_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="creationemailsubscription",
            name="django_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
