# Generated by Django 2.0.13 on 2021-09-04 16:04

from django.db import migrations


def fill_ids(apps, schema_editor):
    CreationEmailSubscription = apps.get_model("ddcz", "CreationEmailSubscription")
    i = 1
    for relation in CreationEmailSubscription.objects.all():
        # can't do instance.save since that would check for integrity of PK
        CreationEmailSubscription.objects.filter(
            user_profile_id=relation.user_profile_id,
            creative_page_slug=relation.creative_page_slug,
        ).update(django_id=i)
        i += 1


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0111_creationemailsubscription_django_id"),
    ]

    operations = [
        migrations.RunPython(fill_ids),
    ]
