# Generated by Django 2.0.13 on 2021-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0115_emaillist_autofield"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedEmail",
            fields=[
                (
                    "email_hash",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnsubscribedEmail",
            fields=[
                (
                    "user_profile_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("token_secret", models.CharField(max_length=255)),
            ],
        ),
    ]
