# Generated by Django 2.0.13 on 2021-09-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0116_blacklistedemail_unsubscribedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledemail",
            name="user_profile_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
