# Generated by Django 2.0.13 on 2021-09-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0117_scheduledemail_user_profile_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UnsubscribedEmail",
            new_name="EmailSubscriptionAuth",
        ),
    ]
