# Generated by Django 2.0.13 on 2022-01-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddcz", "0118_auto_20210905_2029"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreationVotes",
            new_name="CreationVote",
        ),
    ]
