# Generated by Django 2.0.13 on 2022-01-09 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0119_votes_singular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creationvote",
            old_name="creative_page_name",
            new_name="creative_page_slug",
        ),
        migrations.AlterUniqueTogether(
            name="creationvote",
            unique_together={("user_profile_id", "creation_id", "creative_page_slug")},
        ),
    ]
