# Generated by Django 2.0.13 on 2022-01-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0125_creationvote_autofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creationvote",
            name="user_profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to="ddcz.UserProfile",
                db_column="id_uz",
                db_constraint=False,
            ),
        ),
        migrations.RenameField("CreationVote", "user_profile_id", "user_profile"),
        migrations.AlterUniqueTogether(
            name="creationvote",
            unique_together={("user_profile", "creation_id", "creative_page_slug")},
        ),
    ]
