# Generated by Django 2.0.13 on 2023-09-17 17:20

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0129_comment_reputation_default_20230917_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rune",
            name="text",
            field=ddcz.models.magic.MisencodedTextField(db_column="venovani"),
        ),
    ]
